### ISSUE TITLE
error from lme model

### ISSUE THREAD

**Issue by dmcglinn** [radchenkoa5/Exposure-of-Nanobubble-Ozonation-on-Red-Drum#2]
Getting the following error from : 

```r
lin3 <- lmer(log1p(Chl.a) ~ factor(Treatment1) + Temp + factor(Time) + Salinity + pH  + (1|Tank) + (1|Sample), data = chlwq, REML = F)
Error in eval(predvars, data, env) : object 'Sample' not found
```
It appears that the column `Sample` is not defined in the dataframe `chlwq`

**Comment by radchenkoa5** [comment]
Hi Dan,

Interesting that it is giving you an error, it did give me one at first, but I redefined it in my data frame, and got it to work before uploading it. It recognizes sample for me.

**Comment by radchenkoa5** [comment]
I have been choosing a model mostly based on AIC and loglikelihood values, but it is still not plotting as I would like through the data with a line equation that would be helpful.

**Comment by dmcglinn** [comment]
You can see that this file does not have a column called `Sample`
https://github.com/radchenkoa5/Exposure-of-Nanobubble-Ozonation-on-Red-Drum/blob/master/Data/ChlaWQReplicateAcuteData1.csv

**Comment by radchenkoa5** [comment]
Hi Dan,

I must have not synced the new file once I added it. It is still just local, sorry I'll fix that.

**Comment by radchenkoa5** [comment]
You're correct, it is not in the dataset itself, I created it in my code and added it to the data frame. Is there a way to edit the file itself, or is it fine to exist in the new data frame created in the code?

**Comment by dmcglinn** [comment]
I've looked at your data a bit more now graphically and it seems right now that a mixed-model really isn't that useful if Tank is the only random variable. Which in this case I think is the only one that makes sense. The fit is much better for a traditional lm model in which you use Tank as a main effect rather than as a random effect. We can chat about this more this week.
