### ISSUE TITLE
Clean up mess in defining derived variables

### ISSUE THREAD

**Issue by dmcglinn** [radchenkoa5/Exposure-of-Nanobubble-Ozonation-on-Red-Drum#3]
In reference to a question from #2, it is fine to define variables in your code rather than explicitly in raw data sheets. In fact this is preferred because it means that we always know exactly how that derived variable was created. That being said there is a mess on lines: 

https://github.com/radchenkoa5/Exposure-of-Nanobubble-Ozonation-on-Red-Drum/blob/master/Scripts/Linear%20Mixed%20Effects%20Model%20Chlorophyll.Rmd#L80-L88

that needs to be cleaned up. 

Why are you standardizing the categorical treatment variable if you are going to later treat it as a factor when carrying out model building? Note here that factor == categorical variable which means that each level of the variable is treated as just a unique value. so it doesn't matter if there are standardized or not. 

Also it seems like you don't quite understand the difference between the function `cbind` and `data.frame`. The function `cbind` is used to create a matrix from different vectors by appending them as columns. Note a matrix must be homogeneous so all datatypes of the same class. The function `data.frame` can also carry out a column append but it has the benefit or not requiring all the classes be the same type.  

It would seem like the following would suffice for those lines reference above: 
```r
chlwq$Sample <- with(chlwq, factor(paste(Tank, Date, sep = ":")))
chlwq$Chl.a1 <- log1p(chlwq$Chl.a)
```

**Comment by radchenkoa5** [comment]
Hi Dan,

Thank you I will fix it, I standardized the treatment values because I received an error about scaling variables. So I tried to scale a few different variables and my error went away when I scaled the treatment. Since treatment is a percent volume ozonated, do you think it is necessary to treat it as a categorical variable, or leave it continuous?
